export const SUBSCRIPTION_ADD = 'SUBSCRIPTION_ADD';
export const SUBSCRIPTION_INACTIVE = 'SUBSCRIPTION_INACTIVE';
export const SUBSCRIPTION_ACTIVE = 'SUBSCRIPTION_ACTIVE';
export const SUBSCRIPTION_CLEAR = 'SUBSCRIPTION_CLEAR';
export const SUBSCRIPTION_LOAD_STORAGE = 'SUBSCRIPTION_LOAD_STORAGE';
